Try without the added option.
Error was:

```
Execution failed for task ':app:androidDependencies'.
> Could not resolve all artifacts for configuration ':app:debugUnitTestCompileClasspath'.
   > Could not resolve org.mockito:mockito-core:2.27.+.
     Required by:
         project :app
      > Failed to list versions for org.mockito:mockito-core.
         > Unable to load Maven meta-data from https://repo.maven.apache.org/maven2/org/mockito/mockito-core/maven-metadata.xml.
            > org.xml.sax.SAXNotRecognizedException: Property 'http://javax.xml.XMLConstants/property/accessExternalSchema' is not recognized.
```

-- https://app.circleci.com/pipelines/circleci/7G8nuZ3dkcDF4wqYFGMEQR/GuHU3YynmqrR3kjv3HaaQp/139/workflows/f912a4a2-6c27-4144-9a65-5ed487e33218/jobs/139